### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by walterheck** [anjlab/logback-hipchat-appender#2]
Hi,

I'm trying to use this appender for puppetlabs' puppetserver. That is obviously a third party application, so I don't have access to it's source code. I'm completely oblivious to Java, but I would like to use this Hipchat appender. I'm probably not the only person in this situation, it would be really good if your readme contained a section for people in my situation. Even if that says you have to recompile the Java app, that at least gives me something :)

thanks!

**Comment by dmitrygusev** [comment]
I somehow missed this issue, sorry. It was a long time ago, and probably not relevant already, but still.

You don't have to recompile the app to use this appender, you need to update your `logback.xml` and include this appender there. Obviously, appender's JAR should be on classpath or your app.

If you're not familiar how to configure appenders for logback you probably better start here:
http://logback.qos.ch/documentation.html
